#!/usr/bin/env python3
from gradelib import *
import re

r = Runner(save("xv6-aging-simple.out"))

def parse(outputs: str):
    result = []
    for line in outputs.splitlines():
        if "procstatelog" in line:
            result.append(line)
    return result

@test(10, "aging-check")
def test_simple_aging():
    r.run_qemu(shell_script(["mp2-aging 100"]))   # 建立一個 Runner 物件，跑 xv6
    out = r.qemu.output # xv6 shell 裡執行指令 mp2-aging 100

    logs = parse(out)
    assert logs, "No procstatelog lines found."
    # 偵測 priority 是否增加
    pattern = re.compile(r"pid=(\d+).*priority=(\d+)")
    priorities = {}
    for line in logs:
        m = pattern.search(line)
        if not m: continue
        pid, pr = int(m.group(1)), int(m.group(2))
        if pid not in priorities:
            priorities[pid] = []
        priorities[pid].append(pr)

    for pid, pr_list in priorities.items():
        if len(pr_list) < 2:
            continue
        assert pr_list[-1] >= pr_list[0], f"Process {pid} did not age (priority {pr_list[0]}→{pr_list[-1]})"

run_tests()
